apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: demo-put-target
  namespace: fly-points
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: cleardata/fly-points-demo-put-target
